[tool.poetry]
name = "iamcompact-vetting"
version = "0.1.0"
description = "Vetting checks for model outputs in the HORIZON EUROPE project IAM COMPACT"
authors = ["Jan Ivar Korsbakken <janko@cicero.oslo.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyam-iamc = ">=2.1"

[tool.poetry.group.dev.dependencies]
ipython = ">=8.20.0"
pytest = ">=8.0.0"
ipykernel = ">=6.29.0"
dvc = {extras = ["ssh"], version = "^3.48.4"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
