"""Tests for the timeseries_criteria_core module."""
# Partially Generated by CodiumAI

import unittest
import unittest.mock

import pandas as pd
import pyam

from iamcompact_vetting.iam.timeseries_criteria_core \
    import pyam_series_comparison


class TestPyamSeriesComparison(unittest.TestCase):
    """Tests for the pyam_series_comparison decorator."""

    # Converts units of iamdf1 to match iamdf2 when match_units is True
    def test_converts_units_when_match_units_is_true(self):
        @pyam_series_comparison(match_units=True)
        def custom_comparison(series1: pd.Series, series2: pd.Series) -> pd.Series:
            return series1 + series2

        with unittest.mock.patch(
                'iamcompact_vetting.pyam_helpers.make_consistent_units'
        ) as mock_make_consistent_units:
            mock_make_consistent_units.side_effect = lambda df, match_df: df

            iamdf1 = pyam.IamDataFrame(
                pd.DataFrame(
                    {
                        'model': ['model1']*3,
                        'scenario': ['scenario1']*3,
                        'region': ['World']*3,
                        'variable': ['variable1']*3,
                        'unit': ['unit1']*3,
                        'year': [2020, 2025, 2030],
                        'value': [1, 2, 3]
                    }
                )
            )
            iamdf2 = pyam.IamDataFrame(
                pd.DataFrame(
                    {
                        'model': ['model1']*3,
                        'scenario': ['scenario1']*3,
                        'region': ['World']*3,
                        'variable': ['variable1']*3,
                        'unit': ['unit2']*3,
                        'year': [2020, 2025, 2030],
                        'value': [4, 5, 6]
                    }
                )
            )

            result = custom_comparison(iamdf1, iamdf2)

            mock_make_consistent_units.assert_called_once_with(df=iamdf1, match_df=iamdf2)
    ###END def TestPyamSeriesComparison.test_converts_units_when_match_units_is_true

###END class TestPyamSeriesComparison
